# -*- coding: utf-8 -*-
"""task01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G-a9VdMAs2FO140RFDOu7gW4prCeF3oP
"""

#Task 01
import heapq


with open('/content/drive/MyDrive/221Lab_INPUT OUTPUT/Lab_06/input1_2.txt', 'r') as f_in, open('/content/drive/MyDrive/221Lab_INPUT OUTPUT/Lab_06/output1_2.txt', 'w') as f_out:

    n, m = map(int, f_in.readline().split())
    adj = [[] for _ in range(n)]
    for i in range(m):
        u, v, w = map(int, f_in.readline().split())
        adj[u-1].append((v-1, w))
    s = int(f_in.readline()) - 1


    dist = [float('inf')]*n
    dist[s] = 0
    visited = set()


    pq = [(0, s)]

    while pq:
        d, u = heapq.heappop(pq)
        if u in visited:
            continue
        visited.add(u)
        for v, w in adj[u]:
            if dist[v] > d + w:
                dist[v] = d + w
                heapq.heappush(pq, (dist[v], v))

    for d in dist:
        f_out.write(str(d) if d != float('inf') else '-1')
        f_out.write(' ')