# -*- coding: utf-8 -*-
"""task03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G-a9VdMAs2FO140RFDOu7gW4prCeF3oP
"""

#Task 03

import heapq

with open("/content/drive/MyDrive/221Lab_INPUT OUTPUT/Lab_06/input3_1.txt", "r") as f:
    n, m = map(int, f.readline().split())
    graph = [[] for _ in range(n)]
    for i in range(m):
        u, v, w = map(int, f.readline().split())
        graph[u-1].append((v-1, w))
        graph[v-1].append((u-1, w))

dist = [float('inf')] * n
dist[0] = 0
visited = set()

pq = [(0, 0)]

while pq:
    d, u = heapq.heappop(pq)
    if u in visited:
        continue
    visited.add(u)
    for v, w in graph[u]:
        if max(dist[u], w) < dist[v]:
            dist[v] = max(dist[u], w)
            heapq.heappush(pq, (dist[v], v))

with open("/content/drive/MyDrive/221Lab_INPUT OUTPUT/Lab_06/output3_1.txt", "w") as f:
    if dist[-1] != float('inf'):
        f.write(str(dist[-1]))
    else:
        f.write("Impossible")