# -*- coding: utf-8 -*-
"""#Task_01(i).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s-IuIMWhpCX_BWeVoCx_XQqtNtuHsVH3
"""

#Task_01(i)

def quickSort(arr, low, high):
    if low < high:
        
        pi = partition(arr, low, high)
        quickSort(arr, low, pi-1)  
        quickSort(arr, pi+1, high)  

def partition(arr, low, high):
    
    pivot = arr[high]
    i = low-1  

    for j in range(low, high):
        
        if arr[j] < pivot:
            i += 1
            
            arr[i], arr[j] = arr[j], arr[i]

    
    arr[i+1], arr[high] = arr[high], arr[i+1]
    return i+1


with open("/content/drive/MyDrive/221Lab_INPUT OUTPUT/Lab_03/Input_01_i.txt", "r") as f:
    arr = list(map(int, f.readline().split()))


quickSort(arr, 0, len(arr)-1)


with open("/content/drive/MyDrive/221Lab_INPUT OUTPUT/Lab_03/Output_01_i.txt", "w") as f:
    f.write(" ".join(map(str, arr)))