# -*- coding: utf-8 -*-
"""Task 3_(a).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s-IuIMWhpCX_BWeVoCx_XQqtNtuHsVH3
"""

# Task 3_(a)
patient_queue = []

def enqueue(name, priority):
    patient_queue.append((name, priority))

    for i in range(len(patient_queue) - 1):
        for j in range(len(patient_queue) - i - 1):
            if patient_queue[j][1] <= patient_queue[j + 1][1]:
                continue
            patient_queue[j], patient_queue[j + 1] = patient_queue[j + 1], patient_queue[j]


def seeDoctor():
    if not patient_queue:
        print("No patients in the queue.")
    else:
        next_patient = patient_queue.pop(0)
        print(next_patient[0], "is seeing the doctor now.")


def printQueue():
    if not patient_queue:
        print("No patients in the queue.")
    else:
        print("Current patient queue:")
        for i in range(len(patient_queue)):
            print(patient_queue[i][0], "with priority", patient_queue[i][1])


enqueue("ABC", 3)
enqueue("EWQ", 3)
enqueue("SDF", 2)
enqueue("KLM", 1)
seeDoctor()
seeDoctor()
enqueue("FDS", 1)
enqueue("OPN", 3)
enqueue("TYU", 3)
seeDoctor()
enqueue("XCV", 2)
seeDoctor()
seeDoctor()

printQueue()