# -*- coding: utf-8 -*-
"""Task_03(c).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s-IuIMWhpCX_BWeVoCx_XQqtNtuHsVH3
"""

#Task_03(c)

""" From 3a and 3b, we can see that calling seeDoctor from bubble sort and heap sort sometimes gives different results. 
    Because, Heap sort is not stable like bubble sort. Bubble sort keeps track of where things are. 
    If two values are the same, the one that was entered first will be used. 
    But heap sort isn't stable, and it doesn't remember the order in which the values were put in, even if the values are the same. 
    This means that it sometimes shows a different value."""