# -*- coding: utf-8 -*-
"""Task_01(ii).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s-IuIMWhpCX_BWeVoCx_XQqtNtuHsVH3
"""

#Task_01(ii)

def findK(arr, k):
    
    if k < 1 or k > len(arr):
        return None
    
    
    def partition(arr, low, high):
       
        pivot = arr[high]
        i = low - 1
        
        
        for j in range(low, high):
            if arr[j] <= pivot:
                
                i += 1
                arr[i], arr[j] = arr[j], arr[i]
        
        
        arr[i+1], arr[high] = arr[high], arr[i+1]
        
        return i+1
    
    
    low = 0
    high = len(arr) - 1
    
    while True:
        pi = partition(arr, low, high)
        
        if pi == k-1:
            return arr[pi]
        elif pi < k-1:
            low = pi + 1
        else:
            high = pi - 1


with open("/content/drive/MyDrive/221Lab_INPUT OUTPUT/Lab_03/Input_01_ii.txt", "r") as f:
    arr = list(map(int, f.readline().split()))


result1 = findK(arr, 5)
result2 = findK(arr, 7)
result3 = findK(arr, 2)

with open("/content/drive/MyDrive/221Lab_INPUT OUTPUT/Lab_03/Output_01_ii.txt", "a") as f:
    
    f.write(str(result1) + "\n")
    f.write(str(result2) + "\n")
    f.write(str(result3) + "\n")