# -*- coding: utf-8 -*-
"""Task_03(b).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s-IuIMWhpCX_BWeVoCx_XQqtNtuHsVH3
"""

#Task_03(b)

class PatientQueue:
    def __init__(self):
        self.queue = []

    def enqueue(self, name, priority):
        self.queue.append((name, priority))
        self.queue.sort(key=lambda x: x[1])

    def seeDoctor(self, out_file):
        if len(self.queue) != 0:
            name, priority = self.queue.pop(0)
            out_file.write("Patient {} with priority {} has seen the doctor\n".format(name, priority))
        else:
            out_file.write("No patients in the queue\n")

    def printQueue(self, output_file):
        if len(self.queue) != 0:
            for i, patient in enumerate(self.queue):
                output_file.write(
                    "Patient {} with priority {} is at position {}\n".format(patient[0], patient[1], i + 1))
        else:
            output_file.write("No patients in the queue\n")


patient_queue = PatientQueue()

with open("/content/drive/MyDrive/221Lab_INPUT OUTPUT/Lab_03/input_03(b).txt", "r") as input_file, open(
        "/content/drive/MyDrive/221Lab_INPUT OUTPUT/Lab_03/output_03(a).txt", "w") as output_file:
    for line in input_file:
        line = line.strip()
        if line != "see doctor":
            name, priority = line.split()
            patient_queue.enqueue(name, int(priority))
            output_file.write("Patient {} with priority {} has been added to the queue\n".format(name, priority))
        else:
            patient_queue.seeDoctor(output_file)