# -*- coding: utf-8 -*-
"""Task_03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d9GP5_CRSpWS71WHRvJL5QD2VpmyQWgK
"""

#task_03

def merge_sort(X):
    if len(X) <= 1:
        return
    mid = len(X) // 2
    left_arr = X[:mid]
    right_arr = X[mid:]
    merge_sort(left_arr)
    merge_sort(right_arr)
    i = j = k = 0
    while i < len(left_arr) and j < len(right_arr):
        if left_arr[i] <= right_arr[j]:
            X[k] = right_arr[j]
            j += 1
        else:
            X[k] = left_arr[i]
            i += 1
        k += 1
    while i < len(left_arr):
        X[k] = left_arr[i]
        i += 1
        k += 1
    while len(right_arr) > j:
        X[k] = right_arr[j]
        j += 1
        k += 1


with open('/content/drive/MyDrive/221Lab_INPUT OUTPUT/Lab_04/Input_03_02.txt', 'r') as f:
    n = int(f.readline())
    arr = list(map(int, f.readline().split()))

merge_sort(arr)

with open('/content/drive/MyDrive/221Lab_INPUT OUTPUT/Lab_04/Output_03_02.txt', 'w') as f:
    f.write(str(arr[0]))